# Generated by Django 5.2.1 on 2025-06-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="medical_history",
            field=models.TextField(default="Sin historial médico registrado"),
        ),
    ]
