# Generated by Django 5.2.1 on 2025-06-05 05:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="start_of_career",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
